export const configurableFieldNames = [
  "fullName",
  "jobTitle",
  "company",
  "department",
  "email",
  "phone",
  "website",
  "address",
  "pronouns",
  "legalText",
  "logoUrl",
  "photoUrl",
] as const;

export type ConfigurableFieldName = (typeof configurableFieldNames)[number];

type TemplateCatalogEntry = {
  id: string;
  label: string;
  cardTitle: string;
  note: string;
  supportedFields: readonly ConfigurableFieldName[];
};

export const templateCatalog = [
  {
    id: "minimal",
    label: "Minimal",
    cardTitle: "Executive",
    note: "Direct, clean, corporate",
    supportedFields: [
      "fullName",
      "jobTitle",
      "company",
      "email",
      "phone",
      "website",
      "address",
      "pronouns",
    ],
  },
  {
    id: "professional-logo",
    label: "Professional logo",
    cardTitle: "Brand Focus",
    note: "Logo-first and professional",
    supportedFields: [
      "fullName",
      "jobTitle",
      "company",
      "department",
      "email",
      "phone",
      "website",
      "address",
      "pronouns",
      "logoUrl",
    ],
  },
  {
    id: "professional-photo",
    label: "Professional photo",
    cardTitle: "Founder",
    note: "Human, warm, personal",
    supportedFields: [
      "fullName",
      "jobTitle",
      "company",
      "email",
      "phone",
      "website",
      "address",
      "pronouns",
      "legalText",
      "photoUrl",
    ],
  },
  {
    id: "administrative-area",
    label: "Administrative area",
    cardTitle: "Operations",
    note: "Functional and team-oriented",
    supportedFields: [
      "fullName",
      "jobTitle",
      "company",
      "department",
      "email",
      "phone",
      "website",
      "address",
      "pronouns",
      "legalText",
    ],
  },
  {
    id: "scripted-intro",
    label: "Scripted intro",
    cardTitle: "Elegant Intro",
    note: "Handwritten greeting and profile",
    supportedFields: [
      "fullName",
      "jobTitle",
      "company",
      "email",
      "phone",
      "website",
      "address",
      "pronouns",
      "photoUrl",
    ],
  },
  {
    id: "bold-banner",
    label: "Bold banner",
    cardTitle: "Corado Bold",
    note: "Strong split layout with emphasis",
    supportedFields: [
      "fullName",
      "jobTitle",
      "company",
      "department",
      "email",
      "phone",
      "website",
      "address",
      "pronouns",
      "logoUrl",
      "photoUrl",
    ],
  },
  {
    id: "promo-banner",
    label: "Promo banner",
    cardTitle: "Marketing CTA",
    note: "Contact details with promo strip",
    supportedFields: [
      "fullName",
      "jobTitle",
      "company",
      "email",
      "phone",
      "website",
      "address",
      "pronouns",
      "photoUrl",
    ],
  },
  {
    id: "team-column",
    label: "Team column",
    cardTitle: "Team Column",
    note: "Compact corporate roster style",
    supportedFields: [
      "fullName",
      "jobTitle",
      "company",
      "department",
      "email",
      "phone",
      "website",
      "address",
      "pronouns",
      "logoUrl",
      "photoUrl",
    ],
  },
  {
    id: "orb-profile",
    label: "Orb profile",
    cardTitle: "Atlas Glow",
    note: "Rounded badge with social row",
    supportedFields: [
      "fullName",
      "jobTitle",
      "company",
      "department",
      "email",
      "phone",
      "website",
      "address",
      "pronouns",
      "logoUrl",
      "photoUrl",
    ],
  },
  {
    id: "scholar-strip",
    label: "Scholar strip",
    cardTitle: "Scholar Panel",
    note: "Academic or consulting profile",
    supportedFields: [
      "fullName",
      "jobTitle",
      "company",
      "department",
      "email",
      "phone",
      "website",
      "address",
      "pronouns",
      "photoUrl",
    ],
  },
  {
    id: "property-cta",
    label: "Property CTA",
    cardTitle: "Property CTA",
    note: "Real-estate card with call to action",
    supportedFields: [
      "fullName",
      "jobTitle",
      "company",
      "email",
      "phone",
      "website",
      "address",
      "pronouns",
      "photoUrl",
    ],
  },
  {
    id: "social-stack",
    label: "Social stack",
    cardTitle: "Creator Stack",
    note: "Vertical social rail and soft badge",
    supportedFields: [
      "fullName",
      "jobTitle",
      "company",
      "email",
      "phone",
      "website",
      "address",
      "pronouns",
    ],
  },
  {
    id: "executive-card",
    label: "Executive card",
    cardTitle: "Executive Slate",
    note: "Sharp portrait card with CTA",
    supportedFields: [
      "fullName",
      "jobTitle",
      "company",
      "department",
      "email",
      "phone",
      "website",
      "address",
      "pronouns",
      "photoUrl",
    ],
  },
  {
    id: "legal-brief",
    label: "Legal brief",
    cardTitle: "Legal Brief",
    note: "Counsel layout with trust accents",
    supportedFields: [
      "fullName",
      "jobTitle",
      "company",
      "department",
      "email",
      "phone",
      "website",
      "address",
      "pronouns",
      "legalText",
      "photoUrl",
    ],
  },
  {
    id: "medical-profile",
    label: "Medical profile",
    cardTitle: "Care Profile",
    note: "Healthcare-ready structure",
    supportedFields: [
      "fullName",
      "jobTitle",
      "company",
      "department",
      "email",
      "phone",
      "website",
      "address",
      "pronouns",
      "photoUrl",
    ],
  },
  {
    id: "holiday-postcard",
    label: "Holiday postcard",
    cardTitle: "Holiday Note",
    note: "Seasonal greeting with bright promo",
    supportedFields: [
      "fullName",
      "jobTitle",
      "company",
      "email",
      "phone",
      "website",
      "address",
      "pronouns",
      "photoUrl",
    ],
  },
] as const satisfies readonly TemplateCatalogEntry[];

export type TemplateId = (typeof templateCatalog)[number]["id"];

export const templateIds = templateCatalog.map((template) => template.id);

export const templateFieldSupport = Object.fromEntries(
  templateCatalog.map((template) => [template.id, template.supportedFields]),
) as unknown as Record<TemplateId, readonly ConfigurableFieldName[]>;
